/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login_page;

import worker_page.Worker_menu;
import boss_page.Boss_menu;
import client_page.Client_menu;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Bolek
 */
public class login extends javax.swing.JFrame {
    
    private int user_id;
    DataBaseConnector dataConnection = new DataBaseConnector();
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edtLogin = new javax.swing.JTextField();
        edtPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JButton();
        workerBtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Witaj, ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("w systemie sprzedaży");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Login");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Hasło");

        edtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtLoginActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogin.setText("Zaloguj się");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        workerBtn.setText("Pracownik");
        workerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(workerBtn)
                .addGap(132, 132, 132))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edtLogin)
                                    .addComponent(edtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(edtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(workerBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtLoginActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if(workerBtn.isSelected()){
               try{
                        // PRACOWOWNIK
                        // Inicjalizacja JDBC
                        Class.forName(dataConnection.getClassName());
                        Connection con = DriverManager.getConnection(dataConnection.getURL(), dataConnection.getUser(), dataConnection.getPassword());

                        // Stworzenie klauzuli wybierającej nazwę i hasło prwcownika
                        // Obecnie Imie i nazwisko z widoku pracwonicy_view
                        String sql = "Select * from konta_pracownikow_view where login=? and haslo=?";
                        PreparedStatement pst = con.prepareStatement(sql);
                        pst.setString(1, edtLogin.getText());
                        pst.setString(2, edtPassword.getText());
                        ResultSet rs = pst.executeQuery();

                        // PRACOWNIK
                        // Użytkownik znaleziony w bazie danych
                        if(rs.next()) {
                            
                            if(rs.getString(3).equals("KIEROWNIK")){
                                
                            JOptionPane.showMessageDialog(null, "Zalogowano");
                            Boss_menu boss= new Boss_menu();
                            boss.setVisible(true);
                            setVisible(false);
                            }
                            
                            else{
                            JOptionPane.showMessageDialog(null, "Zalogowano");
                            Worker_menu worker= new Worker_menu();
                            //worker.setWorker_connection(dataConnection);
                            worker.setVisible(true);
                            setVisible(false);
                            // System.out.println(rs.getString(3));
                            }
                        }
                        // Błąd danych logowania
                        else {
                            JOptionPane.showMessageDialog(null, "Nazwa użytkownika lub hasło są nieprawidłowe!");
                        }

                    }
                    catch(Exception e){
                        System.out.println(e.getMessage()); 
                    }
            }
            else{
                try{
                        // KLIENT
                        // Inicjalizacja JDBC
                        Class.forName(dataConnection.getClassName());
                        Connection con = DriverManager.getConnection(dataConnection.getURL(), dataConnection.getUser(), dataConnection.getPassword());

                        // Stworzenie klauzuli wybierającej nazwę i hasło użytkownika
                        // Obecnie Imie i nazwisko z tabeli uzytkownicy
                        String sql = "Select * from konta_klientow_view where login=? and haslo=?";
                        PreparedStatement pst = con.prepareStatement(sql);
                        pst.setString(1, edtLogin.getText());
                        pst.setString(2, edtPassword.getText());
                        ResultSet rs = pst.executeQuery();

                        // Użytkownik znaleziony w bazie danych
                        if(rs.next()) {
                            JOptionPane.showMessageDialog(null, "Zalogowano");
                            Client_menu client= new Client_menu();
                            user_id = rs.getInt("id");
                           // System.out.println(user_id);
                            try{
                                String user = "Select klient.id from klient where uzytkownik_id=?";
                                PreparedStatement pst_user = con.prepareStatement(user);
                                pst_user.setInt(1, user_id);
                                ResultSet rs_user = pst_user.executeQuery();
                                if(rs_user.next()){
                                    client.client_id = rs_user.getInt("id");
                                    //System.out.println(client.client_id);
                                }
                            }
                            catch(Exception e){
                                 System.out.println(e.getMessage()); 
                            }

                            // Ustawianie tego samego połączenia w aplikacji klienta
                            client.show_id();
                            client.setVisible(true);
                            setVisible(false);
                        }
                        // Błąd danych logowania
                        else {
                            JOptionPane.showMessageDialog(null, "Nazwa użytkownika lub hasło są nieprawidłowe!");
                        }

                    }
                    catch(Exception e){
                        System.out.println(e.getMessage()); 
                    }
            }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void workerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JTextField edtLogin;
    private javax.swing.JPasswordField edtPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton workerBtn;
    // End of variables declaration//GEN-END:variables
}
