/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boss_page;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login_page.DataBaseConnector;
import worker_page.worker_product;

/**
 *
 * @author Bolek
 */
public class Boss_menu extends javax.swing.JFrame {

    DataBaseConnector boss_data_connection = new DataBaseConnector();
    int selected = 0;
    
    public void setBoss_data_connection(DataBaseConnector boss_data_connection) {
        this.boss_data_connection = boss_data_connection;
    }
    
    // Odczyt danych z bazy do tabeli
    public ArrayList<boss_worker> workersList(){
        ArrayList<boss_worker> workerList = new ArrayList<>();
         try{
             Class.forName(boss_data_connection.getClassName());
             Connection con = DriverManager.getConnection(boss_data_connection.getURL(), boss_data_connection.getUser(), boss_data_connection.getPassword());
             String query1="Select * from dane_pracownikow_view";
             
             Statement st= con.createStatement();
             ResultSet rs= st.executeQuery(query1);
             boss_worker worker;
             while(rs.next()){
                 worker= new boss_worker(rs.getInt("id"), rs.getInt("uzytkownik_id"), rs.getString("imie"), rs.getString("nazwisko"), rs.getString("typ_konta"));
                 workerList.add(worker);
                }
             } 
         catch(Exception e){
                        System.out.println(e.getMessage()); 
          }
         return workerList;
    }
    
        // Wyświetlanie w tabeli
    public void show_worker(){
    ArrayList<boss_worker> list = workersList();
    DefaultTableModel model= (DefaultTableModel)workerTable.getModel();
    model.setRowCount(0);
    Object[] row= new Object[5];
    for(int i=0; i<list.size(); i++){
        row[0]= list.get(i).getId();
        row[1]= list.get(i).getUzytkownik_id();
        row[2]= list.get(i).getImie();
        row[3]= list.get(i).getNazwisko();
        row[4]= list.get(i).getTyp_konta();
        model.addRow(row);
        }
    list.clear();
    }
    
        // Odczyt danych z bazy do tabeli
    public ArrayList<worker_product> productList(){
        ArrayList<worker_product> productList = new ArrayList<>();
         try{
             Class.forName(boss_data_connection.getClassName());
             Connection con = DriverManager.getConnection(boss_data_connection.getURL(), boss_data_connection.getUser(), boss_data_connection.getPassword());
             String query1="Select * from produkty_w_magazynach_view";
             
             Statement st= con.createStatement();
             ResultSet rs= st.executeQuery(query1);
             worker_product product;
             while(rs.next()){
                 product= new worker_product(rs.getInt("id"), rs.getString("nazwa"), rs.getFloat("cena"), rs.getInt("ilosc"), rs.getInt("magazyn_id"));
                 productList.add(product);
                }
             } 
         catch(Exception e){
                        System.out.println(e.getMessage()); 
          }
         return productList;
    }
    
    // Wyświetlanie w tabeli
    public void show_product(){
    ArrayList<worker_product> list = productList();
    DefaultTableModel model= (DefaultTableModel)productTable.getModel();
    model.setRowCount(0);
    Object[] row= new Object[4];
    for(int i=0; i<list.size(); i++){
        row[0]= list.get(i).getNazwa();
        row[1]= list.get(i).getCena();
        row[2]= list.get(i).getIlosc();
        row[3]= list.get(i).getMagazyn();
        model.addRow(row);
        }
     list.clear();
    }
    
    
    /**
     * Creates new form Boss_menu
     */
    public Boss_menu() {
        initComponents();
        show_worker();
        show_product();
        displayStatistics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workerTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        newWorkerbtn = new javax.swing.JButton();
        editWorkerbtn = new javax.swing.JButton();
        deleteWorkerbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        orderCount = new javax.swing.JTextField();
        magazynyField = new javax.swing.JTextField();
        pracownikField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        artykulyField = new javax.swing.JTextField();
        refreshBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        workerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identyfikator", "ID użytkownika", "Imie", "Nazwisko", "Rola"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(workerTable);
        if (workerTable.getColumnModel().getColumnCount() > 0) {
            workerTable.getColumnModel().getColumn(0).setResizable(false);
            workerTable.getColumnModel().getColumn(1).setResizable(false);
            workerTable.getColumnModel().getColumn(2).setResizable(false);
            workerTable.getColumnModel().getColumn(3).setResizable(false);
            workerTable.getColumnModel().getColumn(4).setResizable(false);
        }

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nazwa produktu", "Cena", "Ilość w magazynach", "Magazyn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(productTable);

        jLabel1.setText("Zalogowano jako kierownik");

        newWorkerbtn.setText("Dodaj pracownika");
        newWorkerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWorkerbtnActionPerformed(evt);
            }
        });

        editWorkerbtn.setText("Edytuj dane pracownika");
        editWorkerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editWorkerbtnActionPerformed(evt);
            }
        });

        deleteWorkerbtn.setText("Zwolnij pracownika");
        deleteWorkerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteWorkerbtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("STATYSTYKI");

        jLabel3.setText("Ilość zamówień");

        jLabel4.setText("Ilość magazynów");

        jLabel5.setText("Ilość pracowników");

        orderCount.setEditable(false);

        magazynyField.setEditable(false);

        pracownikField.setEditable(false);

        jLabel6.setText("Ilość artykułów");

        artykulyField.setEditable(false);

        refreshBtn.setText("Odśwież");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(newWorkerbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel2))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderCount, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(magazynyField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pracownikField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(artykulyField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refreshBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteWorkerbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editWorkerbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newWorkerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editWorkerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(deleteWorkerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(orderCount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(3, 3, 3)
                        .addComponent(magazynyField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pracownikField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(artykulyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newWorkerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWorkerbtnActionPerformed
        new_Worker panel= new new_Worker();
        setVisible(true);
        panel.setVisible(true);
    }//GEN-LAST:event_newWorkerbtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        show_worker();
        show_product();
        displayStatistics();
    }//GEN-LAST:event_refreshBtnActionPerformed
    
    private void deleteWorkerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteWorkerbtnActionPerformed

        try{
                        
            int dialogResult = JOptionPane.showConfirmDialog(null, "Czy na pewno chcesz zwolnić tego pracownika?", "Uwaga", JOptionPane.YES_NO_OPTION);
            
            if(dialogResult == JOptionPane.YES_OPTION)
            {
                        Class.forName(boss_data_connection.getClassName());
                        Connection con = DriverManager.getConnection(boss_data_connection.getURL(), boss_data_connection.getUser(), boss_data_connection.getPassword());

                        String insert1 = "DELETE FROM pracownik WHERE uzytkownik_id=?";
                        PreparedStatement pst = con.prepareStatement(insert1);
                        pst.setString(1, workerTable.getValueAt(selected, 1).toString());
                        pst.executeUpdate();
                        
                        PreparedStatement pst2 = con.prepareStatement("DELETE FROM uzytkownik WHERE id=?");
                        pst2.setString(1, workerTable.getValueAt(selected, 1).toString());
                        pst2.executeUpdate();

                        JOptionPane.showMessageDialog(null, "Usunięcie powiodło się!");
            }
                    }
                    catch(Exception e){
                        System.out.println(e.getMessage()); 
                        JOptionPane.showMessageDialog(null, "Błąd!");
                    }
        
    }//GEN-LAST:event_deleteWorkerbtnActionPerformed
  
    private void editWorkerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editWorkerbtnActionPerformed
        
        boss_edit_worker panel= new boss_edit_worker();
       // panel.id_num=Integer.parseInt(idEditWorker.getText());
        panel.id_num= (int)workerTable.getValueAt(selected, 1);
        setVisible(true);
        panel.setVisible(true);


    }//GEN-LAST:event_editWorkerbtnActionPerformed

    private void workerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workerTableMouseClicked
        // TODO add your handling code here:
        selected = workerTable.getSelectedRow();
        //System.out.println(selected);
    }//GEN-LAST:event_workerTableMouseClicked

     private void displayStatistics() {
        try {
        
         Class.forName(boss_data_connection.getClassName());
         Connection con = DriverManager.getConnection(boss_data_connection.getURL(), boss_data_connection.getUser(), boss_data_connection.getPassword());
         PreparedStatement pst = con.prepareStatement("SELECT COUNT(status) AS licznik FROM zamowienie WHERE status NOT LIKE 'Zakończony'");
         ResultSet rs=pst.executeQuery();
         
        int count=0;
        while(rs.next()){
        count= rs.getInt("licznik");
        }
       
        orderCount.setText(String.valueOf(count));
        
         pst = con.prepareStatement("SELECT COUNT(id) AS licznik2 FROM magazyn");
         rs=pst.executeQuery();
         
        int count2=0;
        while(rs.next()){
        count2= rs.getInt("licznik2");
        }
       
        magazynyField.setText(String.valueOf(count2));
        
        
         pst = con.prepareStatement("SELECT COUNT(id) AS licznik3 FROM pracownik");
         rs=pst.executeQuery();
         
        int count3=0;
        while(rs.next()){
        count3= rs.getInt("licznik3");
        }
       
        pracownikField.setText(String.valueOf(count3));
        
        
        pst = con.prepareStatement("SELECT COUNT(id) AS licznik4 FROM produkt");
         rs=pst.executeQuery();
         
        int count4=0;
        while(rs.next()){
        count4= rs.getInt("licznik4");
        }
       
        artykulyField.setText(String.valueOf(count4));
        
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Błąd!");

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Boss_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Boss_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Boss_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Boss_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Boss_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField artykulyField;
    private javax.swing.JButton deleteWorkerbtn;
    private javax.swing.JButton editWorkerbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField magazynyField;
    private javax.swing.JButton newWorkerbtn;
    private javax.swing.JTextField orderCount;
    private javax.swing.JTextField pracownikField;
    private javax.swing.JTable productTable;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTable workerTable;
    // End of variables declaration//GEN-END:variables
}
