/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boss_page;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import login_page.DataBaseConnector;

/**
 *
 * @author Tomek
 */
public class boss_edit_worker extends javax.swing.JFrame {

    DataBaseConnector dataConnection = new DataBaseConnector();
    public int id_num;
    private String typ_konta="";
    /**
     * Creates new form boss_edit_worker
     */
    public boss_edit_worker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TypeComboBox = new javax.swing.JComboBox<>();
        PasswordEdt = new javax.swing.JTextField();
        LoginEdt = new javax.swing.JTextField();
        NameEdt = new javax.swing.JTextField();
        SurnameEdt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameBtn = new javax.swing.JButton();
        surnameBtn = new javax.swing.JButton();
        typeBtn = new javax.swing.JButton();
        hasloBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Edytuj pracownika");

        TypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pracownik", "Kierownik" }));
        TypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeComboBoxActionPerformed(evt);
            }
        });

        LoginEdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginEdtActionPerformed(evt);
            }
        });

        NameEdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameEdtActionPerformed(evt);
            }
        });

        jLabel2.setText("Imie");

        jLabel3.setText("Nazwisko");

        jLabel4.setText("Login");

        jLabel5.setText("Hasło");

        jLabel6.setText("Typ Konta");

        nameBtn.setText("Imie");
        nameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameBtnActionPerformed(evt);
            }
        });

        surnameBtn.setText("Nazwisko");
        surnameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameBtnActionPerformed(evt);
            }
        });

        typeBtn.setText("typ konta");
        typeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeBtnActionPerformed(evt);
            }
        });

        hasloBtn.setText("hasło");
        hasloBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasloBtnActionPerformed(evt);
            }
        });

        loginBtn.setText("login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameEdt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginEdt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(PasswordEdt, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                        .addComponent(SurnameEdt))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(nameBtn)
                .addGap(76, 76, 76)
                .addComponent(surnameBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(typeBtn)
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(loginBtn)
                .addGap(85, 85, 85)
                .addComponent(hasloBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(NameEdt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SurnameEdt, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameBtn)
                    .addComponent(surnameBtn)
                    .addComponent(typeBtn))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordEdt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginEdt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasloBtn)
                    .addComponent(loginBtn))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeComboBoxActionPerformed
        int type = 1;
        typ_konta="";
        type = TypeComboBox.getSelectedIndex()+1;
        if (type == 1) {
            typ_konta += "PRACOWNIK";
        }
        if(type==2){
            typ_konta += "KIEROWNIK";
        }
    }//GEN-LAST:event_TypeComboBoxActionPerformed

    private void LoginEdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginEdtActionPerformed
        
    }//GEN-LAST:event_LoginEdtActionPerformed

    private void NameEdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameEdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameEdtActionPerformed

    private void nameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameBtnActionPerformed
        if (!NameEdt.getText().isEmpty()) {
            if (!NameEdt.getText().matches("[a-zA-Z]+")) {
                JOptionPane.showMessageDialog(null, "Błąd formatu danych!");
                return;
            }
            try {
                Class.forName(dataConnection.getClassName());
                Connection con = DriverManager.getConnection(dataConnection.getURL(), dataConnection.getUser(), dataConnection.getPassword());

                PreparedStatement pst = con.prepareStatement("UPDATE uzytkownik SET imie=? WHERE id=?");
                pst.setString(1, NameEdt.getText());
                pst.setInt(2, id_num);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Zaktualizowano imie pracownika!");

            } catch (Exception e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, "Błąd!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nie imienia loginu!");
        }
    }//GEN-LAST:event_nameBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        if (!LoginEdt.getText().isEmpty()) {
            try {
                Class.forName(dataConnection.getClassName());
                Connection con = DriverManager.getConnection(dataConnection.getURL(), dataConnection.getUser(), dataConnection.getPassword());

                PreparedStatement pst = con.prepareStatement("UPDATE uzytkownik SET login=? WHERE id=?");
                pst.setString(1, LoginEdt.getText());
                pst.setInt(2, id_num);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Zaktualizowano login pracownika!");

            } catch (Exception e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, "Błąd!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nie podano loginu!");
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void surnameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameBtnActionPerformed
      if (!SurnameEdt.getText().isEmpty()) {
          if (!SurnameEdt.getText().matches("[a-zA-Z]+")) {
                JOptionPane.showMessageDialog(null, "Błąd formatu danych!");
                return;
            }
            try {
                Class.forName(dataConnection.getClassName());
                Connection con = DriverManager.getConnection(dataConnection.getURL(), dataConnection.getUser(), dataConnection.getPassword());

                PreparedStatement pst = con.prepareStatement("UPDATE uzytkownik SET nazwisko=? WHERE id=?");
                pst.setString(1, SurnameEdt.getText());
                pst.setInt(2, id_num);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Zaktualizowano nazwisko pracownika!");

            } catch (Exception e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, "Błąd!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nie podano nazwiska!");
        }
    }//GEN-LAST:event_surnameBtnActionPerformed

    private void typeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeBtnActionPerformed
           if (!typ_konta.equals("")) {
            try {
                Class.forName(dataConnection.getClassName());
                Connection con = DriverManager.getConnection(dataConnection.getURL(), dataConnection.getUser(), dataConnection.getPassword());

                PreparedStatement pst = con.prepareStatement("UPDATE pracownik SET typ_konta=? WHERE uzytkownik_id=?");
                pst.setString(1, typ_konta);
                pst.setInt(2, id_num);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Zaktualizowano typ konta pracownika!");

            } catch (Exception e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, "Błąd!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nie wybrano typu!");
        }
    }//GEN-LAST:event_typeBtnActionPerformed

    private void hasloBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasloBtnActionPerformed
            if (!PasswordEdt.getText().isEmpty()) {
            try {
                Class.forName(dataConnection.getClassName());
                Connection con = DriverManager.getConnection(dataConnection.getURL(), dataConnection.getUser(), dataConnection.getPassword());

                PreparedStatement pst = con.prepareStatement("UPDATE uzytkownik SET haslo=? WHERE id=?");
                pst.setString(1, PasswordEdt.getText());
                pst.setInt(2, id_num);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Zaktualizowano hasło pracownika!");

            } catch (Exception e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, "Błąd!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nie podano hasła!");
        }
    }//GEN-LAST:event_hasloBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(boss_edit_worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(boss_edit_worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(boss_edit_worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(boss_edit_worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new boss_edit_worker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LoginEdt;
    private javax.swing.JTextField NameEdt;
    private javax.swing.JTextField PasswordEdt;
    private javax.swing.JTextField SurnameEdt;
    private javax.swing.JComboBox<String> TypeComboBox;
    private javax.swing.JButton hasloBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton nameBtn;
    private javax.swing.JButton surnameBtn;
    private javax.swing.JButton typeBtn;
    // End of variables declaration//GEN-END:variables
}
