/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package worker_page;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import login_page.DataBaseConnector;

/**
 *
 * @author Bolek
 */
public class Edit_product_panel extends javax.swing.JFrame {

    DataBaseConnector dataConnection = new DataBaseConnector();
    
    /**
     * Creates new form Edit_product_panel
     */
    public Edit_product_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameEdt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        numberEdt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        priceEdt = new javax.swing.JTextField();
        PassedBtn = new javax.swing.JButton();
        idProductEdt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel1.setText("Nazwa");

        nameEdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameEdtActionPerformed(evt);
            }
        });

        jLabel2.setText("Ilość");

        numberEdt.setEditable(false);
        numberEdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberEdtActionPerformed(evt);
            }
        });

        jLabel3.setText("Cena");

        priceEdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceEdtActionPerformed(evt);
            }
        });

        PassedBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PassedBtn.setText("Potwierdź");
        PassedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassedBtnActionPerformed(evt);
            }
        });

        idProductEdt.setEditable(false);
        idProductEdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProductEdtActionPerformed(evt);
            }
        });

        jLabel7.setText("ID");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Edycja produktu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(priceEdt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameEdt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberEdt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(jLabel3)
                        .addComponent(jLabel8)
                        .addComponent(idProductEdt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(PassedBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(4, 4, 4)
                .addComponent(idProductEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(priceEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(PassedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameEdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameEdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameEdtActionPerformed

    private void numberEdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberEdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberEdtActionPerformed

    private void priceEdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceEdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceEdtActionPerformed

    private void PassedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassedBtnActionPerformed
        // TODO add your handling code here:
        if(priceEdt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Puste pole cena!");
                return;
            }
        if(!priceEdt.getText().matches("^(\\d*\\.?\\d*)$")){
                JOptionPane.showMessageDialog(null, "Błędny format danych pole cena!");
                return;
            }
        if (nameEdt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Puste pole nazwa!");
                return;
            }
         try{

                        Class.forName(dataConnection.getClassName());
                        Connection con = DriverManager.getConnection(dataConnection.getURL(), dataConnection.getUser(), dataConnection.getPassword());

                        String insert1 = "UPDATE produkt SET nazwa=?, cena=? WHERE id=?";
                        PreparedStatement pst = con.prepareStatement(insert1);
                        pst.setString(1, nameEdt.getText());
                        pst.setString(2, priceEdt.getText());
                        pst.setString(3, idProductEdt.getText());
                        pst.executeUpdate();
                        
                        JOptionPane.showMessageDialog(null, "Edycja powiodła się!");

                    }
                    catch(Exception e){
                        System.out.println(e.getMessage()); 
                        JOptionPane.showMessageDialog(null, "Błąd!");
                    }
        
    }//GEN-LAST:event_PassedBtnActionPerformed

    private void idProductEdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProductEdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProductEdtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_product_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_product_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_product_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_product_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_product_panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PassedBtn;
    public javax.swing.JTextField idProductEdt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField nameEdt;
    public javax.swing.JTextField numberEdt;
    public javax.swing.JTextField priceEdt;
    // End of variables declaration//GEN-END:variables
}
