/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package worker_page;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import login_page.DataBaseConnector;

/**
 *
 * @author Bolek
 */
public class Edit_deliverer_panel extends javax.swing.JFrame {

    DataBaseConnector dataConnection = new DataBaseConnector();
    
    
    /**
     * Creates new form Edit_deliverer_panel
     */
    public Edit_deliverer_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        delivererIdEdt = new javax.swing.JTextField();
        nameEdt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        priceEdt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        waitTimeEdt = new javax.swing.JTextField();
        PassedBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Edycja dostawcy");

        jLabel2.setText("ID");

        jLabel3.setText("Nazwa");

        delivererIdEdt.setEditable(false);
        delivererIdEdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delivererIdEdtActionPerformed(evt);
            }
        });

        nameEdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameEdtActionPerformed(evt);
            }
        });

        jLabel4.setText("Cena");

        priceEdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceEdtActionPerformed(evt);
            }
        });

        jLabel5.setText("Czas oczekiwania");

        waitTimeEdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waitTimeEdtActionPerformed(evt);
            }
        });

        PassedBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PassedBtn.setText("Potwierdź");
        PassedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassedBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(delivererIdEdt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameEdt, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceEdt)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(0, 105, Short.MAX_VALUE))
                            .addComponent(waitTimeEdt))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(PassedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delivererIdEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waitTimeEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PassedBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delivererIdEdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delivererIdEdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delivererIdEdtActionPerformed

    private void nameEdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameEdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameEdtActionPerformed

    private void priceEdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceEdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceEdtActionPerformed

    private void waitTimeEdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waitTimeEdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waitTimeEdtActionPerformed

    private void PassedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassedBtnActionPerformed
        // TODO add your handling code here:
        if(nameEdt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Puste pole nazwa!");
                return;
            }
        if(!nameEdt.getText().matches("[a-zA-Z]+")){
                JOptionPane.showMessageDialog(null, "Błędny format danych pole nazwa!");
                return;
            }
        
        if(waitTimeEdt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Puste pole czas oczekiwania!");
                return;
            }
        if(!waitTimeEdt.getText().matches("[0-9]+")){
                JOptionPane.showMessageDialog(null, "Błędny format danych pole czas oczekiwania!");
                return;
            }
        if(Integer.valueOf(waitTimeEdt.getText())>=32){
                JOptionPane.showMessageDialog(null, "Błędny format danych pole czas oczekiwania!");
                return;
            }
        if(priceEdt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Puste pole cena!");
                return;
            }
        if(!priceEdt.getText().matches("^(\\d*\\.?\\d*)$")){
                JOptionPane.showMessageDialog(null, "Błędny format danych pole cena!");
                return;
            }
        try{

                        Class.forName(dataConnection.getClassName());
                        Connection con = DriverManager.getConnection(dataConnection.getURL(), dataConnection.getUser(), dataConnection.getPassword());

                        String insert1 = "UPDATE dostawca SET nazwa=?, cena=?, czas_oczekiwania_dni=? WHERE id=?";
                        PreparedStatement pst = con.prepareStatement(insert1);
                        pst.setString(1, nameEdt.getText());
                        pst.setString(2, priceEdt.getText());
                        pst.setString(3, waitTimeEdt.getText());
                        pst.setString(4, delivererIdEdt.getText());
                        pst.executeUpdate();
                        
                        JOptionPane.showMessageDialog(null, "Edycja powiodła się!");

                    }
                    catch(Exception e){
                        System.out.println(e.getMessage()); 
                        JOptionPane.showMessageDialog(null, "Błąd!");
                    }
        
        
    }//GEN-LAST:event_PassedBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_deliverer_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_deliverer_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_deliverer_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_deliverer_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_deliverer_panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PassedBtn;
    public javax.swing.JTextField delivererIdEdt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField nameEdt;
    public javax.swing.JTextField priceEdt;
    public javax.swing.JTextField waitTimeEdt;
    // End of variables declaration//GEN-END:variables
}
