/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package worker_page;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import login_page.DataBaseConnector;

/**
 *
 * @author Bolek
 */
public class New_product_panel extends javax.swing.JFrame {

    DataBaseConnector dataConnection = new DataBaseConnector();
    private int magazyn_id = 0;
    private int kategoria_id = 0;
    
    /**
     * Creates new form New_product_panel
     */
    public New_product_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoryComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        nameEdt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        priceEdt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        numberEdt = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        magazynComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionEdt = new javax.swing.JTextArea();

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Usługi", "Przedsiębiorca", "Brak" }));
        categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Kategoria");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Kreator produktu");

        jLabel3.setText("Nazwa");

        nameEdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameEdtActionPerformed(evt);
            }
        });

        jLabel4.setText("Cena (oddziel \".\" kropką)");

        jLabel5.setText("Opis");

        jLabel6.setText("Magazyn");

        jLabel7.setText("Ilość");

        createBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createBtn.setText("Stwórz");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        magazynComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Warszawa", "Kraków", "Poznań", "Wrocław" }));
        magazynComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                magazynComboBoxActionPerformed(evt);
            }
        });

        descriptionEdt.setColumns(20);
        descriptionEdt.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        descriptionEdt.setLineWrap(true);
        descriptionEdt.setRows(5);
        jScrollPane1.setViewportView(descriptionEdt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jScrollPane1))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(priceEdt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(239, 239, 239)
                                            .addComponent(jLabel6))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(nameEdt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel1)
                                                .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(101, 101, 101)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel7)
                                                .addComponent(numberEdt)
                                                .addComponent(magazynComboBox, 0, 141, Short.MAX_VALUE))))
                                    .addGap(3, 3, 3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameEdt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(magazynComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
        // TODO add your handling code here:
       // System.out.println(categoryComboBox.getSelectedIndex());
        kategoria_id = categoryComboBox.getSelectedIndex();

    }//GEN-LAST:event_categoryComboBoxActionPerformed

    private void nameEdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameEdtActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_nameEdtActionPerformed

    private void magazynComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_magazynComboBoxActionPerformed
        // TODO add your handling code here:
       magazyn_id = magazynComboBox.getSelectedIndex();
    }//GEN-LAST:event_magazynComboBoxActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        if(!priceEdt.getText().matches("^(\\d*\\.?\\d*)$")){
                JOptionPane.showMessageDialog(null, "Błędny format danych pole cena!");
                return;
            }
        if(priceEdt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Błędny format danych pole cena!");
                return;
            }
        if (nameEdt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Puste pole nazwa!");
                return;
            }
        if (descriptionEdt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Puste pole opis!");
                return;
            }
        if(numberEdt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Ilość wpisanych sztuk jest pusta!");
                return;
            }
        if(Integer.valueOf(numberEdt.getText())<=0){
                JOptionPane.showMessageDialog(null, "Ilość wpisanych sztuk jest nieprawidłowa!");
                return;
            }
                        try{
                        Class.forName(dataConnection.getClassName());
                        Connection con = DriverManager.getConnection(dataConnection.getURL(), dataConnection.getUser(), dataConnection.getPassword());

                        String insert1 = "INSERT INTO produkt(kategoria_id, nazwa, cena, opis) values(?, ?, ?, ?)";
                        PreparedStatement pst = con.prepareStatement(insert1);
                        pst.setString(1, String.valueOf(kategoria_id + 1));
                        pst.setString(2, nameEdt.getText());
                        pst.setString(3, priceEdt.getText());
                        pst.setString(4, descriptionEdt.getText());
                        pst.executeUpdate();
                        
                        String insert2 = "INSERT INTO magazyn_produkt(magazyn_id , produkt_id , ilosc) values(?, LAST_INSERT_ID(), ?)";
                        PreparedStatement pst2 = con.prepareStatement(insert2);
                        pst2.setString(1, String.valueOf(magazyn_id + 1));
                        pst2.setString(2, numberEdt.getText());
                        pst2.executeUpdate();

                        JOptionPane.showMessageDialog(null, "Dodano produkt!");

                    }
                    catch(Exception e){
                        System.out.println(e.getMessage()); 
                        JOptionPane.showMessageDialog(null, "Błąd!");
                    }
    }//GEN-LAST:event_createBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_product_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_product_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_product_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_product_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_product_panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextArea descriptionEdt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> magazynComboBox;
    private javax.swing.JTextField nameEdt;
    private javax.swing.JTextField numberEdt;
    private javax.swing.JTextField priceEdt;
    // End of variables declaration//GEN-END:variables
}
